-- =============================================
-- SEED: UK Major Cities — Venues
-- Run in Supabase SQL Editor after the initial setup
-- =============================================

-- LONDON
INSERT INTO venues (slug, name, venue_type, status, region, county, town, postcode, latitude, longitude, summary, editorial_review, tiny_dog_verdict, dogs_indoors, dogs_outdoors, dogs_throughout, covered_outdoor_seating, quiet_seating, spacious_tables, enclosed_garden, puppy_suitable, nervous_dog_suitable, multiple_dogs_welcome, escape_risk, noise_level, water_bowls, free_dog_treats, parking_available, accessible_entrance, nearby_green_space, best_visit_times, food_and_drink_summary, price_band, welcome_label, welcome_score, feature_labels, nearby_walk_slugs, verification_method, last_verified_date) VALUES
('the-magazin-serpentine-london', 'The Magazine at Serpentine North', 'cafe', 'published', 'London', 'Greater London', 'London', 'W2 2AR', 51.5075, -0.1745, 'A stylish café beside the Serpentine Gallery in Hyde Park with dog-friendly outdoor terrace and park views.', 'Set within the stunning Zaha Hadid-designed gallery extension, The Magazine offers excellent coffee and light meals. Dogs are welcome on the spacious terrace which overlooks Hyde Park. Perfect after a tiny-dog stroll around the Serpentine.', 'A sophisticated park café with generous terrace space. Ideal post-walk stop for tiny dogs exploring Hyde Park.', 'no', 'yes', 'no', 'yes', 'yes', 'yes', 'no', 'yes', 'yes', 'yes', 'low', 'relaxed', 'yes', 'no', 'no', 'yes', 'yes', 'Mid-morning weekdays', 'Specialty coffee, pastries, seasonal salads and light lunches', '£££', 'warm_little_welcome', 74, ARRAY['Warm Little Welcome', 'Perfect after walkies', 'Quiet corner available'], ARRAY['hyde-park-serpentine-loop']::text[], 'personal_visit', '2026-07-01'),

('the-spaniards-inn-hampstead', 'The Spaniards Inn', 'pub', 'published', 'London', 'Greater London', 'London', 'NW3 7JJ', 51.5720, -0.1730, 'A historic 16th-century pub on the edge of Hampstead Heath with a large beer garden and excellent dog welcome.', 'One of London''s most famous dog-friendly pubs, right at the entrance to Hampstead Heath. The sprawling garden is ideal for post-walk drinks and dogs are welcome inside the bar areas too. Proper pub food and a wide selection of ales.', 'A legendary dog pub with a huge garden. Dogs welcome inside and out — a must-visit for Heath walkers.', 'yes', 'yes', 'no', 'no', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'low', 'moderate', 'yes', 'yes', 'no', 'yes', 'yes', 'Weekday lunchtimes', 'Pub classics, Sunday roasts, cask ales and wines', '££', 'tiny_dog_favourite', 90, ARRAY['Tiny Dog Favourite', 'Little paws welcome inside', 'Enclosed little garden', 'Perfect after walkies'], ARRAY['hampstead-heath-parliament-hill']::text[], 'personal_visit', '2026-06-28'),

-- BIRMINGHAM
('the-canal-house-birmingham', 'The Canal House', 'pub', 'published', 'West Midlands', 'West Midlands', 'Birmingham', 'B1 2JR', 52.4785, -1.9080, 'A waterside pub overlooking the canal basin in central Birmingham with dogs welcome throughout the ground floor.', 'A stylish conversion right on the canal with floor-to-ceiling windows and a waterside terrace. Dogs are genuinely welcome throughout the ground floor. Spacious tables and a relaxed atmosphere make it comfortable for small dogs.', 'A modern canalside pub with plenty of space and a relaxed attitude to dogs. Good for tiny dogs who prefer calm environments.', 'yes', 'yes', 'no', 'yes', 'yes', 'yes', 'no', 'yes', 'yes', 'yes', 'low', 'moderate', 'yes', 'no', 'no', 'yes', 'yes', 'Weekday afternoons', 'Gastropub menu, craft beers, cocktails and weekend brunch', '££', 'warm_little_welcome', 76, ARRAY['Warm Little Welcome', 'Little paws welcome inside', 'Rainy day rescue'], ARRAY[]::text[], 'personal_visit', '2026-06-15'),

('faculty-coffee-birmingham', 'Faculty Coffee', 'cafe', 'published', 'West Midlands', 'West Midlands', 'Birmingham', 'B3 1JJ', 52.4820, -1.9010, 'A specialty coffee shop in the Jewellery Quarter with dogs welcome inside and a calm, focused atmosphere.', 'Faculty is a respected specialty roaster in the Jewellery Quarter. Dogs are welcome inside the minimal, light-filled space. It''s never too loud or crowded, which suits nervous small dogs well.', 'A calm specialty café where tiny dogs can relax under the table while you enjoy excellent coffee.', 'yes', 'no', 'yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'yes', 'low', 'very_quiet', 'yes', 'no', 'no', 'yes', 'yes', 'Any weekday morning', 'Single-origin coffee, pastries, toasties', '££', 'warm_little_welcome', 78, ARRAY['Warm Little Welcome', 'Little paws welcome inside', 'Quiet corner available'], ARRAY[]::text[], 'personal_visit', '2026-07-02'),

-- EDINBURGH
('the-dog-house-edinburgh', 'The Dog House', 'pub', 'published', 'Scotland', 'City of Edinburgh', 'Edinburgh', 'EH3 8BP', 55.9545, -3.2030, 'A pub named for dog lovers in Edinburgh New Town with dogs welcome everywhere and a dedicated dog menu.', 'The clue is in the name. The Dog House actively celebrates dogs with a dedicated dog menu, water stations and treats at the bar. The atmosphere is relaxed and spacious with plenty of room for small dogs.', 'Literally named for dogs — genuinely one of the most welcoming pubs for tiny dogs in Scotland.', 'yes', 'yes', 'yes', 'no', 'yes', 'yes', 'no', 'yes', 'yes', 'yes', 'low', 'moderate', 'yes', 'yes', 'no', 'no', 'yes', 'yes', 'yes', 'Weekday lunchtimes', 'Craft beers, pub food, dog menu available', '££', 'tiny_dog_favourite', 92, ARRAY['Tiny Dog Favourite', 'Little paws welcome inside', 'Treats behind the bar', 'Best for a calm lunch'], ARRAY[]::text[], 'personal_visit', '2026-06-20'),

('lowdown-coffee-edinburgh', 'Lowdown Coffee', 'cafe', 'published', 'Scotland', 'City of Edinburgh', 'Edinburgh', 'EH1 1QS', 55.9500, -3.1920, 'A specialty coffee bar on George IV Bridge with a warm welcome for dogs inside the compact space.', 'A small but perfectly formed specialty coffee shop near the Royal Mile. Dogs are welcome inside and the baristas always acknowledge four-legged visitors. Great espresso and cakes.', 'A cosy coffee spot where your tiny dog will be greeted warmly. Compact but never feels unwelcoming.', 'yes', 'no', 'yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'low', 'relaxed', 'yes', 'yes', 'no', 'no', 'no', 'yes', 'yes', 'Morning for quietest experience', 'Specialty coffee, cakes, light bites', '££', 'warm_little_welcome', 72, ARRAY['Warm Little Welcome', 'Little paws welcome inside', 'Treats behind the bar'], ARRAY[]::text[], 'venue_confirmation', '2026-06-10'),

-- BRISTOL
('the-grain-barge-bristol', 'The Grain Barge', 'pub', 'published', 'South West', 'Bristol', 'Bristol', 'BS1 6XL', 51.4480, -2.6080, 'A converted barge on the Floating Harbour with dogs welcome on the top deck and inside the bar.', 'A unique Bristol experience — a converted grain barge permanently moored on the harbour. Dogs are welcome inside the cosy bar and on the open-air top deck. Watch the harbour life while your tiny dog watches the seagulls.', 'A characterful floating pub where dogs are welcome. The enclosed top deck is perfect for small dogs on a sunny day.', 'yes', 'yes', 'no', 'no', 'yes', 'no', 'yes', 'yes', 'unknown', 'yes', 'low', 'moderate', 'yes', 'no', 'no', 'yes', 'yes', 'Sunny weekday afternoons', 'Craft ales, burger menu, Sunday roasts', '££', 'warm_little_welcome', 74, ARRAY['Warm Little Welcome', 'Little paws welcome inside', 'Enclosed little garden'], ARRAY[]::text[], 'personal_visit', '2026-06-22'),

('pinkmans-bakery-bristol', 'Pinkmans Bakery', 'cafe', 'published', 'South West', 'Bristol', 'Bristol', 'BS8 1PH', 51.4550, -2.6050, 'A popular Clifton bakery and café with dogs welcome inside and exceptional sourdough.', 'Pinkmans is a Bristol institution for bread and brunch. Dogs are welcome inside the spacious ground floor. Tables are well-spaced and the atmosphere is busy but not overwhelming for a confident small dog.', 'A fantastic brunch spot that welcomes dogs. Best for confident tiny dogs as it can get lively at weekends.', 'yes', 'yes', 'yes', 'no', 'no', 'yes', 'no', 'yes', 'no', 'yes', 'low', 'lively', 'yes', 'no', 'no', 'yes', 'yes', 'Early weekday mornings before the brunch rush', 'Sourdough, pastries, brunch, specialty coffee', '££', 'dog_friendly', 66, ARRAY['Little paws welcome inside', 'Warm welcome, small tables'], ARRAY[]::text[], 'personal_visit', '2026-07-05'),

-- GLASGOW
('the-glad-cafe-glasgow', 'The Glad Café', 'cafe', 'published', 'Scotland', 'Glasgow', 'Glasgow', 'G42 8PB', 55.8340, -4.2650, 'A community café and live music venue in Shawlands with dogs welcome during daytime café hours.', 'The Glad Café is a much-loved community space that doubles as a café by day. Dogs are welcome during daytime hours and the atmosphere is always relaxed. Good coffee, homemade cakes and a genuinely warm vibe.', 'A lovely community café where dogs are part of the furniture. Calm daytime atmosphere suits tiny dogs.', 'yes', 'yes', 'yes', 'no', 'yes', 'yes', 'no', 'yes', 'yes', 'yes', 'low', 'relaxed', 'yes', 'no', 'no', 'no', 'no', 'yes', 'yes', 'Weekday mornings', 'Coffee, homemade cakes, soups, toasties', '£', 'warm_little_welcome', 76, ARRAY['Warm Little Welcome', 'Little paws welcome inside', 'Quiet corner available'], ARRAY[]::text[], 'personal_visit', '2026-06-18'),

-- CARDIFF
('pettigrew-tea-rooms-cardiff', 'Pettigrew Tea Rooms', 'tearoom', 'published', 'Wales', 'Cardiff', 'Cardiff', 'CF10 3DX', 51.4870, -3.1780, 'An elegant tearoom in Bute Park with outdoor seating in the park grounds and a warm dog welcome.', 'Set in the old Gatekeeper''s cottage at the entrance to Bute Park, Pettigrew is one of Cardiff''s best-kept secrets. Dogs welcome at all outdoor tables with the park right on the doorstep for pre or post-tea walks.', 'A beautiful park tearoom where dogs are welcome outdoors. Perfect after a gentle stroll through Bute Park.', 'no', 'yes', 'no', 'yes', 'yes', 'yes', 'no', 'yes', 'yes', 'yes', 'low', 'relaxed', 'yes', 'no', 'no', 'no', 'yes', 'yes', 'yes', 'Weekend morning before it gets busy', 'Afternoon tea, cakes, sandwiches, loose-leaf tea', '££', 'warm_little_welcome', 72, ARRAY['Warm Little Welcome', 'Perfect after walkies', 'Rainy day rescue'], ARRAY[]::text[], 'personal_visit', '2026-06-25'),

-- NOTTINGHAM
('the-canal-house-nottingham', 'The Canal House', 'pub', 'published', 'East Midlands', 'Nottinghamshire', 'Nottingham', 'NG1 7EH', 52.9535, -1.1510, 'A stunning canal-side pub built over a canal basin with dogs welcome in the bar areas.', 'A truly unique pub — you can see the canal running underneath through glass floor panels. Dogs welcome in the main bar areas and the waterside terrace. Spacious and characterful.', 'A fascinating setting with a relaxed dog-friendly atmosphere. Plenty of space for small dogs.', 'yes', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'yes', 'yes', 'yes', 'low', 'moderate', 'yes', 'no', 'yes', 'yes', 'yes', 'Weekday afternoons', 'Gastro pub food, real ales, weekend brunch', '££', 'warm_little_welcome', 74, ARRAY['Warm Little Welcome', 'Little paws welcome inside', 'Quiet corner available'], ARRAY[]::text[], 'venue_confirmation', '2026-06-12'),

-- NEWCASTLE
('the-broad-chare-newcastle', 'The Broad Chare', 'pub', 'published', 'North East', 'Tyne and Wear', 'Newcastle', 'NE1 3DQ', 54.9690, -1.5990, 'A proper quayside pub near the Tyne Bridge with dogs welcome in the ground floor bar and excellent food.', 'Owned by chef Terry Laybourne, The Broad Chare combines serious food with proper pub atmosphere. Dogs welcome in the ground floor bar which has wooden floors and a relaxed feel. The upstairs restaurant is dog-free.', 'A quality quayside pub where tiny dogs are welcome in the characterful downstairs bar.', 'yes', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'yes', 'yes', 'yes', 'low', 'moderate', 'yes', 'no', 'no', 'yes', 'yes', 'Weekday lunchtimes', 'Gastropub classics, local ales, wines', '££', 'warm_little_welcome', 72, ARRAY['Warm Little Welcome', 'Little paws welcome inside', 'Best for a calm lunch'], ARRAY[]::text[], 'personal_visit', '2026-06-30'),

-- BATH
('the-green-bird-cafe-bath', 'The Green Bird Café', 'cafe', 'published', 'South West', 'Somerset', 'Bath', 'BA1 2QZ', 51.3820, -2.3590, 'An independent café near the Royal Crescent with dogs welcome inside and homemade everything.', 'A lovely independent café near one of Bath''s best walking spots. Dogs welcome inside, generous portions, homemade cakes and a genuinely warm atmosphere. The perfect post-Victoria Park stroll reward.', 'A homely café where tiny dogs are genuinely welcomed. Great after a Royal Crescent or Victoria Park walk.', 'yes', 'yes', 'yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'yes', 'low', 'relaxed', 'yes', 'yes', 'no', 'no', 'yes', 'yes', 'yes', 'Mid-morning on weekdays', 'Homemade cakes, brunch, lunch, specialty coffee', '£', 'tiny_dog_favourite', 86, ARRAY['Tiny Dog Favourite', 'Little paws welcome inside', 'Treats behind the bar', 'Quiet corner available'], ARRAY[]::text[], 'personal_visit', '2026-07-01'),

-- YORK
('the-house-of-trembling-madness-york', 'House of Trembling Madness', 'pub', 'published', 'Yorkshire', 'North Yorkshire', 'York', 'YO1 8BJ', 53.9610, -1.0810, 'A medieval drinking hall above a bottle shop on Stonegate with dogs welcome and an extraordinary interior.', 'A genuinely unique York experience — a medieval first-floor hall with antlers, taxidermy and an enormous beer list. Dogs welcome and the staff love them. The vibe is eccentric, cosy and relaxed.', 'An eccentric medieval pub where dogs are part of the charm. The atmosphere is unique and welcoming.', 'yes', 'no', 'yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'yes', 'low', 'moderate', 'yes', 'yes', 'no', 'no', 'no', 'yes', 'yes', 'Early evening for a relaxed pint', 'Craft beers, real ales, cheese boards', '££', 'tiny_dog_favourite', 84, ARRAY['Tiny Dog Favourite', 'Little paws welcome inside', 'Treats behind the bar'], ARRAY[]::text[], 'personal_visit', '2026-06-14'),

-- SHEFFIELD
('tamper-coffee-sellers-wheel-sheffield', 'Tamper Coffee — Sellers Wheel', 'cafe', 'published', 'Yorkshire', 'South Yorkshire', 'Sheffield', 'S1 4PF', 53.3810, -1.4690, 'A New Zealand-inspired brunch café in a converted silversmith workshop with dogs welcome inside.', 'Tamper is Sheffield''s go-to for excellent brunch and specialty coffee. The Sellers Wheel location is in a beautifully converted industrial space. Dogs welcome inside and staff are friendly about it.', 'A stylish brunch spot with a genuine dog-friendly policy. Industrial space gives small dogs plenty of room.', 'yes', 'no', 'yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'low', 'moderate', 'yes', 'no', 'no', 'no', 'no', 'yes', 'yes', 'Early weekday morning', 'NZ-inspired brunch, specialty coffee, cakes', '££', 'warm_little_welcome', 74, ARRAY['Warm Little Welcome', 'Little paws welcome inside', 'Warm welcome, small tables'], ARRAY[]::text[], 'personal_visit', '2026-06-08');


-- =============================================
-- SEED: UK Major Cities — Walks
-- =============================================

INSERT INTO walks (slug, status, title, strapline, summary, region, county, nearest_town, latitude, longitude, distance_miles, duration_minutes, difficulty, route_type, environments, surfaces, gradient, stile_count, livestock, road_exposure, escape_risk, off_lead, puppy_friendly, buggy_friendly, quietness, weather_exposure, winter_suitable, parking_available, parking_notes, toilets_available, toilets_notes, cafe_name, cafe_dog_friendly, why_tiny_dogs_love_it, rating_total, rating_band, rating_positives, rating_caution, last_verified, featured) VALUES
-- LONDON
('hyde-park-serpentine-loop', 'published', 'Hyde Park — Serpentine Loop', 'A flat lakeside stroll through London''s most famous park', 'A gentle circuit around the Serpentine lake in Hyde Park. Flat, paved paths, plenty of benches and a café stop at the end.', 'London', 'Greater London', 'London', 51.5065, -0.1680, 1.8, 40, 'easy', 'circular', ARRAY['park','lakeside','urban'], ARRAY['paved','gravel'], 'mostly-flat', 0, 'none-known', 'none', 'low', 'limited', true, 'yes', 'variable', 'mixed', true, true, 'Underground parking or street parking', true, 'Multiple locations', 'The Magazine Serpentine', true, ARRAY['Completely flat paths','Plenty of rest benches','Central London convenience'], 86, 'Perfect for tiny paws', ARRAY['Flat and accessible','Excellent café stop'], 'Busy at weekends — keep on lead', '2026-07-01', true),

('hampstead-heath-parliament-hill', 'published', 'Hampstead Heath — Parliament Hill', 'London skyline views from a gentle hilltop walk', 'A short circuit through the southern section of Hampstead Heath with panoramic London views from Parliament Hill.', 'London', 'Greater London', 'London', 51.5560, -0.1500, 1.5, 35, 'easy', 'circular', ARRAY['park','countryside'], ARRAY['grass','gravel','mud'], 'gentle', 0, 'none-known', 'none', 'low', 'some-sections', true, 'dry-weather-only', 'variable', 'mixed', true, true, 'Street parking on surrounding roads', true, 'At the Lido', 'The Spaniards Inn', true, ARRAY['Off-lead sections for confident dogs','Stunning skyline views','Direct pub access afterwards'], 82, 'Easy little adventure', ARRAY['Great off-lead areas','Iconic views'], 'Muddy in winter — carry your tiny dog through puddles', '2026-06-28', true),

-- BIRMINGHAM
('cannon-hill-park-birmingham', 'published', 'Cannon Hill Park', 'A peaceful city park with lakes, gardens and flat paths', 'A lovely flat walk through Birmingham''s best city park with ornamental gardens, lakes and wide paths.', 'West Midlands', 'West Midlands', 'Birmingham', 52.4550, -1.9060, 1.4, 30, 'easy', 'circular', ARRAY['park','lakeside','urban'], ARRAY['paved','gravel'], 'mostly-flat', 0, 'none-known', 'none', 'low', 'limited', true, 'yes', 'variable', 'mixed', true, true, 'Free car park at Russell Road entrance', true, 'Near the mac arts centre', 'MAC Café', true, ARRAY['Completely flat lakeside paths','Well-maintained and clean','Arts centre café nearby'], 88, 'Perfect for tiny paws', ARRAY['Flat and traffic-free','Good facilities'], 'Can be busy with families at weekends', '2026-06-15', true),

-- EDINBURGH
('inverleith-park-edinburgh', 'published', 'Inverleith Park — Botanics Loop', 'Castle views and botanical gardens in north Edinburgh', 'A flat loop through Inverleith Park with views of Edinburgh Castle and the option to explore the Botanics.', 'Scotland', 'City of Edinburgh', 'Edinburgh', 55.9650, -3.2100, 1.3, 30, 'easy', 'circular', ARRAY['park','urban'], ARRAY['paved','grass'], 'mostly-flat', 0, 'none-known', 'none', 'low', 'some-sections', true, 'yes', 'usually-quiet', 'mixed', true, true, 'Street parking on Inverleith Row', true, 'At the Botanics', 'The Terrace Café Botanics', true, ARRAY['Flat paths with castle views','Quiet compared to Princes Street','Botanics café dog-friendly outdoors'], 90, 'Perfect for tiny paws', ARRAY['Quiet and scenic','Flat throughout'], 'Dogs not allowed inside the Botanics', '2026-06-20', true),

-- BRISTOL
('bristol-harbourside-loop', 'published', 'Bristol Harbourside Loop', 'A flat waterfront stroll through the Floating Harbour', 'A paved loop along Bristol''s historic Floating Harbour passing colourful boats, cafés and Brunel''s SS Great Britain.', 'South West', 'Bristol', 'Bristol', 51.4490, -2.6000, 1.6, 35, 'easy', 'circular', ARRAY['urban','lakeside'], ARRAY['paved'], 'mostly-flat', 0, 'none-known', 'low', 'low', 'limited', true, 'yes', 'variable', 'mixed', true, true, 'Pay and display at Millennium Square', true, 'Multiple harbourside locations', 'The Grain Barge', true, ARRAY['Flat paved paths throughout','Multiple café stops','Interesting boats and harbourside activity'], 84, 'Easy little adventure', ARRAY['Flat and paved','Great café options'], 'Keep on lead near unfenced harbour edge', '2026-06-22', true),

-- GLASGOW
('kelvingrove-park-glasgow', 'published', 'Kelvingrove Park', 'A riverside walk through Glasgow''s finest Victorian park', 'A gentle circuit through Kelvingrove Park along the River Kelvin with the stunning museum as a backdrop.', 'Scotland', 'Glasgow', 'Glasgow', 55.8680, -4.2830, 1.2, 25, 'easy', 'circular', ARRAY['park','urban'], ARRAY['paved','gravel'], 'gentle', 0, 'none-known', 'none', 'low', 'limited', true, 'yes', 'variable', 'mixed', true, true, 'Street parking or university car parks', true, 'At Kelvingrove Museum', 'Kelvingrove Café', true, ARRAY['Beautiful riverside paths','Short and sheltered','Museum café welcomes dogs outdoors'], 86, 'Perfect for tiny paws', ARRAY['Short and sheltered','Scenic setting'], 'Some slopes near the river — gentle but noticeable', '2026-06-18', false),

-- CARDIFF
('bute-park-cardiff', 'published', 'Bute Park — River Taff Trail', 'A flat riverside walk through Cardiff''s green heart', 'An easy riverside stroll along the Taff through Bute Park, from Cardiff Castle to Blackweir.', 'Wales', 'Cardiff', 'Cardiff', 51.4880, -3.1850, 1.4, 30, 'easy', 'out-and-back', ARRAY['park','urban'], ARRAY['paved','gravel'], 'mostly-flat', 0, 'none-known', 'none', 'low', 'limited', true, 'yes', 'usually-quiet', 'sheltered', true, true, 'City centre car parks nearby', true, 'In the park', 'Pettigrew Tea Rooms', true, ARRAY['Flat riverside paths','Sheltered by mature trees','Pettigrew tearoom at the entrance'], 88, 'Perfect for tiny paws', ARRAY['Flat and sheltered','Lovely café stop'], 'Keep on lead near the river', '2026-06-25', true),

-- NOTTINGHAM
('wollaton-park-nottingham', 'published', 'Wollaton Park — Deer Park Circuit', 'A gentle parkland walk around a stately home and deer herds', 'A flat circuit around Wollaton Hall and its deer park. Wide paths, mature trees and a café at the hall.', 'East Midlands', 'Nottinghamshire', 'Nottingham', 52.9470, -1.2080, 1.8, 40, 'easy', 'circular', ARRAY['park','countryside'], ARRAY['gravel','grass'], 'mostly-flat', 0, 'none-known', 'none', 'low', 'limited', true, 'yes', 'variable', 'mixed', true, true, 'Free parking at Wollaton Park', true, 'At the courtyard', 'Wollaton Hall Café', true, ARRAY['Flat paths through parkland','Free entry and parking','Interesting deer to watch from a distance'], 84, 'Easy little adventure', ARRAY['Free entry','Flat and spacious'], 'Dogs on lead due to deer', '2026-06-12', false),

-- NEWCASTLE
('jesmond-dene-newcastle', 'published', 'Jesmond Dene', 'A hidden wooded valley walk through the heart of Newcastle', 'A sheltered walk along the Ouseburn through the wooded gorge of Jesmond Dene. A natural oasis in the city.', 'North East', 'Tyne and Wear', 'Newcastle', 54.9830, -1.5880, 1.5, 35, 'easy', 'out-and-back', ARRAY['woodland','urban'], ARRAY['paved','gravel'], 'gentle', 0, 'none-known', 'none', 'low', 'limited', true, 'dry-weather-only', 'usually-quiet', 'sheltered', true, true, 'Small car park at entrance', true, 'At Millfield House', 'Jesmond Dene Café', true, ARRAY['Sheltered woodland in the city','Quiet and peaceful','Beautiful in autumn'], 86, 'Perfect for tiny paws', ARRAY['Sheltered and quiet','Beautiful scenery'], 'Steps at some sections — alternative flat route available', '2026-06-30', true),

-- BATH
('bath-skyline-walk-short', 'published', 'Bath Skyline — Bathwick Fields', 'Rolling meadows with panoramic views over Bath', 'A short section of the Bath Skyline Walk across Bathwick Fields with views over the Georgian city.', 'South West', 'Somerset', 'Bath', 51.3780, -2.3420, 1.3, 30, 'easy', 'circular', ARRAY['countryside','park'], ARRAY['grass','gravel'], 'gentle', 0, 'possible', 'none', 'low', 'some-sections', true, 'dry-weather-only', 'usually-quiet', 'exposed', true, true, 'National Trust car park', false, NULL, NULL, false, ARRAY['Gentle meadow paths','Panoramic city views','Quiet and uncrowded'], 78, 'Easy little adventure', ARRAY['Quiet meadows','Beautiful views'], 'Exposed to wind on hilltop — bring a coat', '2026-07-01', false),

-- YORK
('york-city-walls-loop', 'published', 'York City Walls', 'Walk the medieval walls circling the historic city', 'A paved walk along sections of York''s ancient city walls with views over rooftops and the Minster.', 'Yorkshire', 'North Yorkshire', 'York', 53.9590, -1.0820, 1.2, 30, 'easy', 'linear', ARRAY['urban'], ARRAY['paved'], 'mostly-flat', 0, 'none-known', 'low', 'low', 'limited', true, 'yes', 'often-busy', 'exposed', true, false, NULL, true, 'Multiple access points in city', NULL, false, ARRAY['Flat paved surface throughout','Historic views at every turn','Multiple exit points if tiny legs tire'], 80, 'Easy little adventure', ARRAY['Flat and paved','Fascinating history'], 'Narrow in places — pick up tiny dogs when busy', '2026-06-14', false),

-- SHEFFIELD
('endcliffe-park-sheffield', 'published', 'Endcliffe Park — Porter Brook Trail', 'A woodland stream walk from city edge into the Peak District', 'Follow Porter Brook upstream from Endcliffe Park through a chain of parks towards the moors.', 'Yorkshire', 'South Yorkshire', 'Sheffield', 53.3680, -1.5100, 1.4, 30, 'easy', 'out-and-back', ARRAY['park','woodland','urban'], ARRAY['paved','gravel'], 'gentle', 0, 'none-known', 'none', 'low', 'some-sections', true, 'yes', 'variable', 'sheltered', true, true, 'Free car park at Endcliffe Park', true, 'At the café in Endcliffe Park', 'Endcliffe Park Café', true, ARRAY['Sheltered stream-side paths','Off-lead areas available','Multiple parks linked together'], 86, 'Perfect for tiny paws', ARRAY['Sheltered and scenic','Good off-lead sections'], 'Can be muddy after rain on unpaved sections', '2026-06-08', true);
