-- =============================================
-- MORE UK WALKS — Run in Supabase SQL Editor
-- Then trigger a Netlify rebuild
-- =============================================

-- LAKE DISTRICT
INSERT INTO walks (slug, status, title, strapline, summary, region, county, nearest_town, latitude, longitude, distance_miles, duration_minutes, difficulty, route_type, environments, surfaces, gradient, stile_count, livestock, road_exposure, escape_risk, off_lead, puppy_friendly, buggy_friendly, quietness, weather_exposure, winter_suitable, parking_available, parking_notes, toilets_available, toilets_notes, cafe_name, cafe_dog_friendly, why_tiny_dogs_love_it, rating_total, rating_band, rating_positives, rating_caution, last_verified, featured)
VALUES ('tarn-hows-ambleside', 'published', 'Tarn Hows', 'A picture-perfect lakeside loop in the heart of the Lakes', 'A gentle circuit around one of the Lake District''s most beautiful tarns. Well-surfaced path with stunning mountain views.', 'North West', 'Cumbria', 'Ambleside', 54.3960, -3.0320, 1.5, 40, 'easy', 'circular', ARRAY['lakeside','woodland','countryside'], ARRAY['gravel','paved'], 'gentle', 0, 'none-known', 'none', 'low', 'limited', true, 'yes', 'variable', 'mixed', true, true, 'National Trust car park (pay and display)', true, 'At the car park', 'Tarn Hows Tea Garden', true, ARRAY['Well-surfaced path suitable for little paws','Sheltered by surrounding trees','Stunning views without strenuous climbing'], 84, 'Easy little adventure', ARRAY['Beautiful scenery','Good surfaces'], 'Can be busy in summer — early morning is best', '2026-07-10', true);

INSERT INTO walks (slug, status, title, strapline, summary, region, county, nearest_town, latitude, longitude, distance_miles, duration_minutes, difficulty, route_type, environments, surfaces, gradient, stile_count, livestock, road_exposure, escape_risk, off_lead, puppy_friendly, buggy_friendly, quietness, weather_exposure, winter_suitable, parking_available, parking_notes, toilets_available, toilets_notes, cafe_name, cafe_dog_friendly, why_tiny_dogs_love_it, rating_total, rating_band, rating_positives, rating_caution, last_verified, featured)
VALUES ('derwentwater-lakeside-keswick', 'published', 'Derwentwater Lakeside — Keswick', 'A flat shoreline stroll with fell views', 'A short section of the Derwentwater lakeside path from Keswick to Friar''s Crag. Flat, paved and dog-friendly.', 'North West', 'Cumbria', 'Keswick', 54.6010, -3.1360, 1.0, 25, 'easy', 'out-and-back', ARRAY['lakeside','park'], ARRAY['paved','gravel'], 'mostly-flat', 0, 'none-known', 'none', 'low', 'limited', true, 'yes', 'variable', 'mixed', true, true, 'Lakeside car park Keswick', true, 'Multiple in Keswick', 'Lakeside Tea Room', true, ARRAY['Completely flat lakeside path','Short enough for the tiniest dogs','Gorgeous views without effort'], 90, 'Perfect for tiny paws', ARRAY['Flat and paved','Stunning lake views'], 'Keep on lead near the water edge', '2026-07-08', true);

-- CORNWALL
INSERT INTO walks (slug, status, title, strapline, summary, region, county, nearest_town, latitude, longitude, distance_miles, duration_minutes, difficulty, route_type, environments, surfaces, gradient, stile_count, livestock, road_exposure, escape_risk, off_lead, puppy_friendly, buggy_friendly, quietness, weather_exposure, winter_suitable, parking_available, parking_notes, toilets_available, toilets_notes, cafe_name, cafe_dog_friendly, why_tiny_dogs_love_it, rating_total, rating_band, rating_positives, rating_caution, last_verified, featured)
VALUES ('maenporth-beach-falmouth', 'published', 'Maenporth Beach', 'A quiet sandy cove perfect for tiny dogs', 'A small sheltered beach near Falmouth with year-round dog access. Firm sand at low tide and a dog-friendly café above.', 'South West', 'Cornwall', 'Falmouth', 50.1290, -5.0820, 0.8, 20, 'easy', 'out-and-back', ARRAY['beach','coast'], ARRAY['sand'], 'mostly-flat', 0, 'none-known', 'none', 'low', 'generally-suitable', true, 'no', 'usually-quiet', 'mixed', true, true, 'Car park above the beach', true, 'At the car park', 'Maenporth Beach Café', true, ARRAY['Small sheltered cove — less overwhelming than big beaches','Year-round dog access','Firm sand easy on tiny paws'], 86, 'Perfect for tiny paws', ARRAY['Quiet sheltered beach','Year-round access'], 'Check tide times — beach shrinks at high tide', '2026-07-05', true);

INSERT INTO walks (slug, status, title, strapline, summary, region, county, nearest_town, latitude, longitude, distance_miles, duration_minutes, difficulty, route_type, environments, surfaces, gradient, stile_count, livestock, road_exposure, escape_risk, off_lead, puppy_friendly, buggy_friendly, quietness, weather_exposure, winter_suitable, parking_available, parking_notes, toilets_available, toilets_notes, cafe_name, cafe_dog_friendly, why_tiny_dogs_love_it, rating_total, rating_band, rating_positives, rating_caution, last_verified, featured)
VALUES ('helford-creek-walk', 'published', 'Helford Creek', 'A sheltered riverside walk through ancient woodland', 'A gentle walk along the north bank of the Helford River through oak woodland. Sheltered, quiet and atmospheric.', 'South West', 'Cornwall', 'Helford', 50.0890, -5.1170, 1.4, 35, 'easy', 'out-and-back', ARRAY['woodland','coast'], ARRAY['gravel','grass'], 'gentle', 0, 'none-known', 'none', 'low', 'some-sections', true, 'dry-weather-only', 'usually-quiet', 'sheltered', true, true, 'Small NT car park', false, NULL, 'Shipwright Arms', true, ARRAY['Sheltered ancient woodland','Quiet and atmospheric','River views without cliff exposure'], 82, 'Easy little adventure', ARRAY['Sheltered and quiet','Beautiful setting'], 'Can be muddy after rain — carry small dogs through puddles', '2026-06-28', false);

-- COTSWOLDS
INSERT INTO walks (slug, status, title, strapline, summary, region, county, nearest_town, latitude, longitude, distance_miles, duration_minutes, difficulty, route_type, environments, surfaces, gradient, stile_count, livestock, road_exposure, escape_risk, off_lead, puppy_friendly, buggy_friendly, quietness, weather_exposure, winter_suitable, parking_available, parking_notes, toilets_available, toilets_notes, cafe_name, cafe_dog_friendly, why_tiny_dogs_love_it, rating_total, rating_band, rating_positives, rating_caution, last_verified, featured)
VALUES ('bourton-on-the-water-riverside', 'published', 'Bourton-on-the-Water — Riverside Walk', 'A gentle stroll along the River Windrush in the Cotswolds', 'A flat riverside walk through the pretty Cotswold village of Bourton-on-the-Water with multiple dog-friendly stops.', 'South West', 'Gloucestershire', 'Bourton-on-the-Water', 51.8820, -1.7520, 1.2, 30, 'easy', 'out-and-back', ARRAY['park','urban'], ARRAY['paved','grass'], 'mostly-flat', 0, 'none-known', 'low', 'low', 'limited', true, 'yes', 'often-busy', 'mixed', true, true, 'Pay and display in village', true, 'In the village', 'The Mousetrap Inn', true, ARRAY['Flat riverside paths','Multiple dog-friendly pubs and cafés','Shallow river for paddling'], 80, 'Easy little adventure', ARRAY['Flat and pretty','Great café options'], 'Very busy in summer — go early or midweek', '2026-07-01', false);

-- PEAK DISTRICT
INSERT INTO walks (slug, status, title, strapline, summary, region, county, nearest_town, latitude, longitude, distance_miles, duration_minutes, difficulty, route_type, environments, surfaces, gradient, stile_count, livestock, road_exposure, escape_risk, off_lead, puppy_friendly, buggy_friendly, quietness, weather_exposure, winter_suitable, parking_available, parking_notes, toilets_available, toilets_notes, cafe_name, cafe_dog_friendly, why_tiny_dogs_love_it, rating_total, rating_band, rating_positives, rating_caution, last_verified, featured)
VALUES ('padley-gorge-grindleford', 'published', 'Padley Gorge', 'A magical woodland walk through a mossy gorge', 'A sheltered walk through ancient oak woodland along Burbage Brook. Stepping stones, mossy rocks and dappled light.', 'East Midlands', 'Derbyshire', 'Grindleford', 53.3080, -1.6290, 1.3, 35, 'easy', 'out-and-back', ARRAY['woodland'], ARRAY['gravel','rock'], 'gentle', 0, 'none-known', 'none', 'low', 'some-sections', true, 'dry-weather-only', 'usually-quiet', 'sheltered', true, true, 'Longshaw Estate NT car park', true, 'At the estate', 'Longshaw Estate Café', true, ARRAY['Sheltered woodland — protected from wind','Fascinating scents and textures','Stream-side paths to explore'], 84, 'Easy little adventure', ARRAY['Sheltered woodland','Quiet and atmospheric'], 'Rocky in places — carry tiny dogs over stepping stones', '2026-06-20', true);

-- NORFOLK
INSERT INTO walks (slug, status, title, strapline, summary, region, county, nearest_town, latitude, longitude, distance_miles, duration_minutes, difficulty, route_type, environments, surfaces, gradient, stile_count, livestock, road_exposure, escape_risk, off_lead, puppy_friendly, buggy_friendly, quietness, weather_exposure, winter_suitable, parking_available, parking_notes, toilets_available, toilets_notes, cafe_name, cafe_dog_friendly, why_tiny_dogs_love_it, rating_total, rating_band, rating_positives, rating_caution, last_verified, featured)
VALUES ('holkham-beach-norfolk', 'published', 'Holkham Beach', 'Vast golden sands and pine-backed dunes', 'A spectacular wide beach backed by pinewoods. Endless space for tiny dogs to explore at low tide.', 'East', 'Norfolk', 'Wells-next-the-Sea', 52.9730, 0.8070, 1.5, 40, 'easy', 'out-and-back', ARRAY['beach','coast','woodland'], ARRAY['sand','boardwalk'], 'mostly-flat', 0, 'none-known', 'none', 'low', 'generally-suitable', true, 'no', 'usually-quiet', 'exposed', false, true, 'Lady Anne''s Drive car park', true, 'At the car park', 'The Victoria Inn', true, ARRAY['Enormous quiet beach — space to run','Firm sand at low tide','Pine woods for shelter'], 80, 'Easy little adventure', ARRAY['Off-lead freedom','Vast quiet space'], 'Very exposed to wind — not great for tiny dogs in winter', '2026-07-01', true);

-- SCOTLAND HIGHLANDS
INSERT INTO walks (slug, status, title, strapline, summary, region, county, nearest_town, latitude, longitude, distance_miles, duration_minutes, difficulty, route_type, environments, surfaces, gradient, stile_count, livestock, road_exposure, escape_risk, off_lead, puppy_friendly, buggy_friendly, quietness, weather_exposure, winter_suitable, parking_available, parking_notes, toilets_available, toilets_notes, cafe_name, cafe_dog_friendly, why_tiny_dogs_love_it, rating_total, rating_band, rating_positives, rating_caution, last_verified, featured)
VALUES ('loch-an-eilein-aviemore', 'published', 'Loch an Eilein', 'A forest lochside circuit in the Cairngorms', 'A flat walk around a beautiful loch surrounded by Caledonian pine forest. Castle island in the middle.', 'Scotland', 'Highland', 'Aviemore', 57.1430, -3.8330, 2.0, 50, 'easy', 'circular', ARRAY['lakeside','woodland'], ARRAY['gravel'], 'mostly-flat', 0, 'none-known', 'none', 'low', 'some-sections', true, 'yes', 'usually-quiet', 'sheltered', true, true, 'Forestry car park (pay and display)', false, NULL, NULL, false, ARRAY['Flat lochside path through ancient forest','Quiet and sheltered by pines','Red squirrels to watch from a distance'], 82, 'Easy little adventure', ARRAY['Flat throughout','Beautifully sheltered'], 'Slightly longer than ideal for very tiny dogs — turn back at halfway', '2026-06-15', true);

-- SUSSEX
INSERT INTO walks (slug, status, title, strapline, summary, region, county, nearest_town, latitude, longitude, distance_miles, duration_minutes, difficulty, route_type, environments, surfaces, gradient, stile_count, livestock, road_exposure, escape_risk, off_lead, puppy_friendly, buggy_friendly, quietness, weather_exposure, winter_suitable, parking_available, parking_notes, toilets_available, toilets_notes, cafe_name, cafe_dog_friendly, why_tiny_dogs_love_it, rating_total, rating_band, rating_positives, rating_caution, last_verified, featured)
VALUES ('sheffield-park-garden-sussex', 'published', 'Sheffield Park Garden', 'Lakes and colour in a National Trust garden', 'A flat walk around the lakes and woodland of Sheffield Park. Stunning autumn colour and well-maintained paths year-round.', 'South East', 'East Sussex', 'Uckfield', 51.0000, -0.0100, 1.5, 40, 'easy', 'circular', ARRAY['park','lakeside','woodland'], ARRAY['gravel','paved'], 'mostly-flat', 0, 'none-known', 'none', 'low', 'limited', true, 'yes', 'variable', 'sheltered', true, true, 'NT car park', true, 'At the visitor centre', 'Sheffield Park Café', true, ARRAY['Beautiful gardens with flat paths','Sheltered by mature trees','Excellent café with outdoor dog seating'], 88, 'Perfect for tiny paws', ARRAY['Flat and beautiful','Great facilities'], 'Dogs on lead throughout the garden', '2026-07-02', false);

-- DORSET
INSERT INTO walks (slug, status, title, strapline, summary, region, county, nearest_town, latitude, longitude, distance_miles, duration_minutes, difficulty, route_type, environments, surfaces, gradient, stile_count, livestock, road_exposure, escape_risk, off_lead, puppy_friendly, buggy_friendly, quietness, weather_exposure, winter_suitable, parking_available, parking_notes, toilets_available, toilets_notes, cafe_name, cafe_dog_friendly, why_tiny_dogs_love_it, rating_total, rating_band, rating_positives, rating_caution, last_verified, featured)
VALUES ('studland-beach-knoll-walk', 'published', 'Studland Beach — Knoll Beach Section', 'Golden sand and sheltered dunes on the Jurassic Coast', 'A dog-friendly section of Studland Beach with soft golden sand and sheltered dunes. Dogs allowed year-round on this section.', 'South West', 'Dorset', 'Studland', 50.6490, -1.9420, 1.2, 30, 'easy', 'out-and-back', ARRAY['beach','coast'], ARRAY['sand'], 'mostly-flat', 0, 'none-known', 'none', 'low', 'generally-suitable', true, 'no', 'variable', 'exposed', false, true, 'National Trust Knoll Beach car park', true, 'At the car park', 'Knoll Beach Café', true, ARRAY['Soft golden sand gentle on paws','Sheltered dunes for nervous dogs','Year-round dog access on this section'], 82, 'Easy little adventure', ARRAY['Dog-friendly all year','Sheltered dunes'], 'Exposed to sea breeze — wrap up tiny dogs', '2026-06-25', true);

-- KENT
INSERT INTO walks (slug, status, title, strapline, summary, region, county, nearest_town, latitude, longitude, distance_miles, duration_minutes, difficulty, route_type, environments, surfaces, gradient, stile_count, livestock, road_exposure, escape_risk, off_lead, puppy_friendly, buggy_friendly, quietness, weather_exposure, winter_suitable, parking_available, parking_notes, toilets_available, toilets_notes, cafe_name, cafe_dog_friendly, why_tiny_dogs_love_it, rating_total, rating_band, rating_positives, rating_caution, last_verified, featured)
VALUES ('bewl-water-reservoir-kent', 'published', 'Bewl Water — Dam Walk', 'A flat waterside stroll at Kent''s largest lake', 'A short section along the dam and shoreline of Bewl Water reservoir. Flat, well-surfaced and peaceful.', 'South East', 'Kent', 'Lamberhurst', 51.0720, 0.3930, 1.4, 30, 'easy', 'out-and-back', ARRAY['lakeside','countryside'], ARRAY['paved','gravel'], 'mostly-flat', 0, 'none-known', 'none', 'low', 'limited', true, 'yes', 'usually-quiet', 'mixed', true, true, 'Bewl Water visitor centre car park', true, 'At the visitor centre', 'Bewl Water Café', true, ARRAY['Flat lakeside path','Quiet midweek','Good facilities and café'], 84, 'Easy little adventure', ARRAY['Flat and peaceful','Good café stop'], 'Keep on lead near the waterside', '2026-07-01', false);

-- OXFORDSHIRE
INSERT INTO walks (slug, status, title, strapline, summary, region, county, nearest_town, latitude, longitude, distance_miles, duration_minutes, difficulty, route_type, environments, surfaces, gradient, stile_count, livestock, road_exposure, escape_risk, off_lead, puppy_friendly, buggy_friendly, quietness, weather_exposure, winter_suitable, parking_available, parking_notes, toilets_available, toilets_notes, cafe_name, cafe_dog_friendly, why_tiny_dogs_love_it, rating_total, rating_band, rating_positives, rating_caution, last_verified, featured)
VALUES ('blenheim-park-woodstock', 'published', 'Blenheim Park — Lakeside Walk', 'Palace grounds with a gentle lakeside circuit', 'A flat walk around Queen Pool and the Grand Bridge in Blenheim Palace parkland. Dogs welcome in the park.', 'South East', 'Oxfordshire', 'Woodstock', 51.8410, -1.3610, 1.6, 40, 'easy', 'circular', ARRAY['park','lakeside'], ARRAY['gravel','grass'], 'mostly-flat', 0, 'none-known', 'none', 'low', 'limited', true, 'yes', 'variable', 'mixed', true, true, 'Blenheim Palace car park (entry fee for park)', true, 'At the palace', 'The Orangery', false, ARRAY['Flat parkland paths','Grand scenery without difficult terrain','Well-maintained surfaces year-round'], 84, 'Easy little adventure', ARRAY['Flat and scenic','Good facilities'], 'Entry fee applies — dogs on lead in the park', '2026-06-30', false);

-- HAMPSHIRE
INSERT INTO walks (slug, status, title, strapline, summary, region, county, nearest_town, latitude, longitude, distance_miles, duration_minutes, difficulty, route_type, environments, surfaces, gradient, stile_count, livestock, road_exposure, escape_risk, off_lead, puppy_friendly, buggy_friendly, quietness, weather_exposure, winter_suitable, parking_available, parking_notes, toilets_available, toilets_notes, cafe_name, cafe_dog_friendly, why_tiny_dogs_love_it, rating_total, rating_band, rating_positives, rating_caution, last_verified, featured)
VALUES ('new-forest-bolderwood-hampshire', 'published', 'New Forest — Bolderwood Deer Sanctuary', 'Ancient woodland with wild ponies and deer viewing', 'A flat walk through ancient New Forest woodland to the deer viewing platform. Wide gravel paths and gentle terrain.', 'South East', 'Hampshire', 'Lyndhurst', 50.8570, -1.5830, 1.3, 30, 'easy', 'circular', ARRAY['woodland','countryside'], ARRAY['gravel'], 'mostly-flat', 0, 'none-known', 'none', 'low', 'limited', true, 'yes', 'usually-quiet', 'sheltered', true, true, 'Forestry England car park', false, NULL, NULL, false, ARRAY['Flat ancient woodland','Sheltered from wind','Wild ponies and deer to observe safely'], 86, 'Perfect for tiny paws', ARRAY['Flat and sheltered','Beautiful ancient woodland'], 'Keep dogs on lead — wild ponies roam freely', '2026-07-05', true);

-- DEVON
INSERT INTO walks (slug, status, title, strapline, summary, region, county, nearest_town, latitude, longitude, distance_miles, duration_minutes, difficulty, route_type, environments, surfaces, gradient, stile_count, livestock, road_exposure, escape_risk, off_lead, puppy_friendly, buggy_friendly, quietness, weather_exposure, winter_suitable, parking_available, parking_notes, toilets_available, toilets_notes, cafe_name, cafe_dog_friendly, why_tiny_dogs_love_it, rating_total, rating_band, rating_positives, rating_caution, last_verified, featured)
VALUES ('dartmouth-castle-walk', 'published', 'Dartmouth Castle Walk', 'A sheltered coastal stroll to a riverside castle', 'A paved walk from Dartmouth town along the estuary to Dartmouth Castle. Flat, sheltered and scenic.', 'South West', 'Devon', 'Dartmouth', 50.3470, -3.5700, 1.0, 25, 'easy', 'out-and-back', ARRAY['coast','urban'], ARRAY['paved'], 'mostly-flat', 0, 'none-known', 'low', 'low', 'limited', true, 'yes', 'variable', 'sheltered', true, false, NULL, true, 'In Dartmouth', 'Dart Marina Restaurant', true, ARRAY['Flat paved path — easy on tiny paws','Sheltered by the estuary hillside','Short enough for the smallest dogs'], 88, 'Perfect for tiny paws', ARRAY['Flat and paved','Sheltered coastal path'], 'Can be busy in summer', '2026-06-22', false);

-- SUFFOLK
INSERT INTO walks (slug, status, title, strapline, summary, region, county, nearest_town, latitude, longitude, distance_miles, duration_minutes, difficulty, route_type, environments, surfaces, gradient, stile_count, livestock, road_exposure, escape_risk, off_lead, puppy_friendly, buggy_friendly, quietness, weather_exposure, winter_suitable, parking_available, parking_notes, toilets_available, toilets_notes, cafe_name, cafe_dog_friendly, why_tiny_dogs_love_it, rating_total, rating_band, rating_positives, rating_caution, last_verified, featured)
VALUES ('southwold-pier-beach', 'published', 'Southwold Pier & Beach', 'A seaside town walk with pier, beach and fish and chips', 'A gentle walk from the iconic pier along Southwold beach. Dogs welcome on the beach year-round.', 'East', 'Suffolk', 'Southwold', 52.3290, 1.6810, 1.2, 30, 'easy', 'out-and-back', ARRAY['beach','coast','urban'], ARRAY['sand','paved'], 'mostly-flat', 0, 'none-known', 'low', 'low', 'limited', true, 'no', 'variable', 'exposed', false, true, 'Town car parks', true, 'In the town', 'The Sole Bay Fish Company', true, ARRAY['Traditional seaside atmosphere','Dogs welcome on the beach','Multiple dog-friendly refreshment stops'], 78, 'Easy little adventure', ARRAY['Dogs welcome on beach','Great town stops'], 'Exposed to sea wind — coat up for tiny dogs', '2026-07-01', false);
