-- =============================================
-- SEED: UK Major Cities
-- Run in Supabase SQL Editor
-- Each INSERT is separate to avoid column-count errors
-- =============================================

-- LONDON: The Magazine Serpentine
INSERT INTO venues (slug, name, venue_type, status, region, county, town, postcode, latitude, longitude, summary, editorial_review, tiny_dog_verdict, dogs_indoors, dogs_outdoors, dogs_throughout, covered_outdoor_seating, quiet_seating, spacious_tables, enclosed_garden, puppy_suitable, nervous_dog_suitable, multiple_dogs_welcome, escape_risk, noise_level, water_bowls, free_dog_treats, parking_available, accessible_entrance, nearby_green_space, best_visit_times, food_and_drink_summary, price_band, welcome_label, welcome_score, feature_labels, nearby_walk_slugs, verification_method, last_verified_date)
VALUES ('the-magazin-serpentine-london', 'The Magazine at Serpentine North', 'cafe', 'published', 'London', 'Greater London', 'London', 'W2 2AR', 51.5075, -0.1745, 'A stylish café beside the Serpentine Gallery in Hyde Park with dog-friendly outdoor terrace.', 'Set within the Zaha Hadid-designed gallery extension. Dogs welcome on the spacious terrace overlooking Hyde Park.', 'A sophisticated park café with generous terrace space. Ideal post-walk stop.', 'no', 'yes', 'no', 'yes', 'yes', 'yes', 'no', 'yes', 'yes', 'yes', 'low', 'relaxed', 'yes', 'no', 'no', 'yes', 'yes', 'Mid-morning weekdays', 'Specialty coffee, pastries, seasonal salads', '£££', 'warm_little_welcome', 74, ARRAY['Warm Little Welcome', 'Perfect after walkies'], ARRAY['hyde-park-serpentine-loop'], 'personal_visit', '2026-07-01');

-- LONDON: The Spaniards Inn
INSERT INTO venues (slug, name, venue_type, status, region, county, town, postcode, latitude, longitude, summary, editorial_review, tiny_dog_verdict, dogs_indoors, dogs_outdoors, dogs_throughout, covered_outdoor_seating, quiet_seating, spacious_tables, enclosed_garden, puppy_suitable, nervous_dog_suitable, multiple_dogs_welcome, escape_risk, noise_level, water_bowls, free_dog_treats, parking_available, accessible_entrance, nearby_green_space, best_visit_times, food_and_drink_summary, price_band, welcome_label, welcome_score, feature_labels, nearby_walk_slugs, verification_method, last_verified_date)
VALUES ('the-spaniards-inn-hampstead', 'The Spaniards Inn', 'pub', 'published', 'London', 'Greater London', 'London', 'NW3 7JJ', 51.5720, -0.1730, 'A historic 16th-century pub on the edge of Hampstead Heath with a large beer garden.', 'One of London''s most famous dog-friendly pubs. Sprawling garden ideal for post-walk drinks.', 'A legendary dog pub with a huge garden. Dogs welcome inside and out.', 'yes', 'yes', 'no', 'no', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'low', 'moderate', 'yes', 'yes', 'no', 'yes', 'yes', 'Weekday lunchtimes', 'Pub classics, Sunday roasts, cask ales', '££', 'tiny_dog_favourite', 90, ARRAY['Tiny Dog Favourite', 'Little paws welcome inside', 'Enclosed little garden'], ARRAY['hampstead-heath-parliament-hill'], 'personal_visit', '2026-06-28');

-- BIRMINGHAM: The Canal House
INSERT INTO venues (slug, name, venue_type, status, region, county, town, postcode, latitude, longitude, summary, editorial_review, tiny_dog_verdict, dogs_indoors, dogs_outdoors, dogs_throughout, covered_outdoor_seating, quiet_seating, spacious_tables, enclosed_garden, puppy_suitable, nervous_dog_suitable, multiple_dogs_welcome, escape_risk, noise_level, water_bowls, free_dog_treats, parking_available, accessible_entrance, nearby_green_space, best_visit_times, food_and_drink_summary, price_band, welcome_label, welcome_score, feature_labels, nearby_walk_slugs, verification_method, last_verified_date)
VALUES ('the-canal-house-birmingham', 'The Canal House', 'pub', 'published', 'West Midlands', 'West Midlands', 'Birmingham', 'B1 2JR', 52.4785, -1.9080, 'A waterside pub overlooking the canal basin with dogs welcome throughout the ground floor.', 'Stylish conversion on the canal with floor-to-ceiling windows and waterside terrace. Dogs welcome throughout ground floor.', 'A modern canalside pub with plenty of space. Good for tiny dogs who prefer calm environments.', 'yes', 'yes', 'no', 'yes', 'yes', 'yes', 'no', 'yes', 'yes', 'yes', 'low', 'moderate', 'yes', 'no', 'no', 'yes', 'yes', 'Weekday afternoons', 'Gastropub menu, craft beers, cocktails', '££', 'warm_little_welcome', 76, ARRAY['Warm Little Welcome', 'Little paws welcome inside', 'Rainy day rescue'], ARRAY[]::text[], 'personal_visit', '2026-06-15');

-- BIRMINGHAM: Faculty Coffee
INSERT INTO venues (slug, name, venue_type, status, region, county, town, postcode, latitude, longitude, summary, editorial_review, tiny_dog_verdict, dogs_indoors, dogs_outdoors, dogs_throughout, covered_outdoor_seating, quiet_seating, spacious_tables, enclosed_garden, puppy_suitable, nervous_dog_suitable, multiple_dogs_welcome, escape_risk, noise_level, water_bowls, free_dog_treats, parking_available, accessible_entrance, nearby_green_space, best_visit_times, food_and_drink_summary, price_band, welcome_label, welcome_score, feature_labels, nearby_walk_slugs, verification_method, last_verified_date)
VALUES ('faculty-coffee-birmingham', 'Faculty Coffee', 'cafe', 'published', 'West Midlands', 'West Midlands', 'Birmingham', 'B3 1JJ', 52.4820, -1.9010, 'A specialty coffee shop in the Jewellery Quarter with dogs welcome inside.', 'Respected specialty roaster. Dogs welcome inside the minimal, light-filled space. Never too loud.', 'A calm specialty café where tiny dogs can relax. Never overwhelmingly busy.', 'yes', 'no', 'yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'yes', 'low', 'very_quiet', 'yes', 'no', 'no', 'yes', 'yes', 'Any weekday morning', 'Single-origin coffee, pastries, toasties', '££', 'warm_little_welcome', 78, ARRAY['Warm Little Welcome', 'Little paws welcome inside', 'Quiet corner available'], ARRAY[]::text[], 'personal_visit', '2026-07-02');

-- EDINBURGH: The Dog House
INSERT INTO venues (slug, name, venue_type, status, region, county, town, postcode, latitude, longitude, summary, editorial_review, tiny_dog_verdict, dogs_indoors, dogs_outdoors, dogs_throughout, covered_outdoor_seating, quiet_seating, spacious_tables, enclosed_garden, puppy_suitable, nervous_dog_suitable, multiple_dogs_welcome, escape_risk, noise_level, water_bowls, free_dog_treats, parking_available, accessible_entrance, nearby_green_space, best_visit_times, food_and_drink_summary, price_band, welcome_label, welcome_score, feature_labels, nearby_walk_slugs, verification_method, last_verified_date)
VALUES ('the-dog-house-edinburgh', 'The Dog House', 'pub', 'published', 'Scotland', 'City of Edinburgh', 'Edinburgh', 'EH3 8BP', 55.9545, -3.2030, 'A pub named for dog lovers with dogs welcome everywhere and a dedicated dog menu.', 'The clue is in the name. Dedicated dog menu, water stations and treats at the bar. Relaxed and spacious.', 'Literally named for dogs — genuinely one of the most welcoming pubs for tiny dogs in Scotland.', 'yes', 'yes', 'yes', 'no', 'yes', 'yes', 'no', 'yes', 'yes', 'yes', 'low', 'moderate', 'yes', 'yes', 'no', 'yes', 'yes', 'Weekday lunchtimes', 'Craft beers, pub food, dog menu available', '££', 'tiny_dog_favourite', 92, ARRAY['Tiny Dog Favourite', 'Little paws welcome inside', 'Treats behind the bar'], ARRAY[]::text[], 'personal_visit', '2026-06-20');

-- EDINBURGH: Lowdown Coffee
INSERT INTO venues (slug, name, venue_type, status, region, county, town, postcode, latitude, longitude, summary, editorial_review, tiny_dog_verdict, dogs_indoors, dogs_outdoors, dogs_throughout, covered_outdoor_seating, quiet_seating, spacious_tables, enclosed_garden, puppy_suitable, nervous_dog_suitable, multiple_dogs_welcome, escape_risk, noise_level, water_bowls, free_dog_treats, parking_available, accessible_entrance, nearby_green_space, best_visit_times, food_and_drink_summary, price_band, welcome_label, welcome_score, feature_labels, nearby_walk_slugs, verification_method, last_verified_date)
VALUES ('lowdown-coffee-edinburgh', 'Lowdown Coffee', 'cafe', 'published', 'Scotland', 'City of Edinburgh', 'Edinburgh', 'EH1 1QS', 55.9500, -3.1920, 'A specialty coffee bar on George IV Bridge with a warm welcome for dogs.', 'Small but perfectly formed. Dogs welcome inside and baristas always greet four-legged visitors.', 'A cosy coffee spot where your tiny dog will be greeted warmly.', 'yes', 'no', 'yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'low', 'relaxed', 'yes', 'yes', 'no', 'yes', 'yes', 'Morning for quietest experience', 'Specialty coffee, cakes, light bites', '££', 'warm_little_welcome', 72, ARRAY['Warm Little Welcome', 'Little paws welcome inside'], ARRAY[]::text[], 'venue_confirmation', '2026-06-10');

-- BRISTOL: The Grain Barge
INSERT INTO venues (slug, name, venue_type, status, region, county, town, postcode, latitude, longitude, summary, editorial_review, tiny_dog_verdict, dogs_indoors, dogs_outdoors, dogs_throughout, covered_outdoor_seating, quiet_seating, spacious_tables, enclosed_garden, puppy_suitable, nervous_dog_suitable, multiple_dogs_welcome, escape_risk, noise_level, water_bowls, free_dog_treats, parking_available, accessible_entrance, nearby_green_space, best_visit_times, food_and_drink_summary, price_band, welcome_label, welcome_score, feature_labels, nearby_walk_slugs, verification_method, last_verified_date)
VALUES ('the-grain-barge-bristol', 'The Grain Barge', 'pub', 'published', 'South West', 'Bristol', 'Bristol', 'BS1 6XL', 51.4480, -2.6080, 'A converted barge on the Floating Harbour with dogs welcome on the top deck and bar.', 'A unique Bristol experience. Dogs welcome inside the cosy bar and on the open-air top deck.', 'A characterful floating pub where dogs are welcome. Enclosed top deck perfect for small dogs.', 'yes', 'yes', 'no', 'no', 'yes', 'no', 'yes', 'yes', 'unknown', 'yes', 'low', 'moderate', 'yes', 'no', 'no', 'yes', 'yes', 'Sunny weekday afternoons', 'Craft ales, burger menu, Sunday roasts', '££', 'warm_little_welcome', 74, ARRAY['Warm Little Welcome', 'Little paws welcome inside'], ARRAY['bristol-harbourside-loop'], 'personal_visit', '2026-06-22');

-- BRISTOL: Pinkmans Bakery
INSERT INTO venues (slug, name, venue_type, status, region, county, town, postcode, latitude, longitude, summary, editorial_review, tiny_dog_verdict, dogs_indoors, dogs_outdoors, dogs_throughout, covered_outdoor_seating, quiet_seating, spacious_tables, enclosed_garden, puppy_suitable, nervous_dog_suitable, multiple_dogs_welcome, escape_risk, noise_level, water_bowls, free_dog_treats, parking_available, accessible_entrance, nearby_green_space, best_visit_times, food_and_drink_summary, price_band, welcome_label, welcome_score, feature_labels, nearby_walk_slugs, verification_method, last_verified_date)
VALUES ('pinkmans-bakery-bristol', 'Pinkmans Bakery', 'cafe', 'published', 'South West', 'Bristol', 'Bristol', 'BS8 1PH', 51.4550, -2.6050, 'A popular Clifton bakery with dogs welcome inside and exceptional sourdough.', 'A Bristol institution for bread and brunch. Dogs welcome inside the spacious ground floor.', 'A fantastic brunch spot that welcomes dogs. Best for confident tiny dogs.', 'yes', 'yes', 'yes', 'no', 'no', 'yes', 'no', 'yes', 'no', 'yes', 'low', 'lively', 'yes', 'no', 'no', 'yes', 'yes', 'Early weekday mornings', 'Sourdough, pastries, brunch, specialty coffee', '££', 'dog_friendly', 66, ARRAY['Little paws welcome inside', 'Warm welcome, small tables'], ARRAY[]::text[], 'personal_visit', '2026-07-05');

-- GLASGOW: The Glad Café
INSERT INTO venues (slug, name, venue_type, status, region, county, town, postcode, latitude, longitude, summary, editorial_review, tiny_dog_verdict, dogs_indoors, dogs_outdoors, dogs_throughout, covered_outdoor_seating, quiet_seating, spacious_tables, enclosed_garden, puppy_suitable, nervous_dog_suitable, multiple_dogs_welcome, escape_risk, noise_level, water_bowls, free_dog_treats, parking_available, accessible_entrance, nearby_green_space, best_visit_times, food_and_drink_summary, price_band, welcome_label, welcome_score, feature_labels, nearby_walk_slugs, verification_method, last_verified_date)
VALUES ('the-glad-cafe-glasgow', 'The Glad Café', 'cafe', 'published', 'Scotland', 'Glasgow', 'Glasgow', 'G42 8PB', 55.8340, -4.2650, 'A community café and live music venue with dogs welcome during daytime hours.', 'A much-loved community space. Dogs welcome during daytime and the atmosphere is always relaxed.', 'A lovely community café where dogs are part of the furniture.', 'yes', 'yes', 'yes', 'no', 'yes', 'yes', 'no', 'yes', 'yes', 'yes', 'low', 'relaxed', 'yes', 'no', 'no', 'yes', 'yes', 'Weekday mornings', 'Coffee, homemade cakes, soups, toasties', '£', 'warm_little_welcome', 76, ARRAY['Warm Little Welcome', 'Little paws welcome inside', 'Quiet corner available'], ARRAY['kelvingrove-park-glasgow'], 'personal_visit', '2026-06-18');

-- CARDIFF: Pettigrew Tea Rooms
INSERT INTO venues (slug, name, venue_type, status, region, county, town, postcode, latitude, longitude, summary, editorial_review, tiny_dog_verdict, dogs_indoors, dogs_outdoors, dogs_throughout, covered_outdoor_seating, quiet_seating, spacious_tables, enclosed_garden, puppy_suitable, nervous_dog_suitable, multiple_dogs_welcome, escape_risk, noise_level, water_bowls, free_dog_treats, parking_available, accessible_entrance, nearby_green_space, best_visit_times, food_and_drink_summary, price_band, welcome_label, welcome_score, feature_labels, nearby_walk_slugs, verification_method, last_verified_date)
VALUES ('pettigrew-tea-rooms-cardiff', 'Pettigrew Tea Rooms', 'tearoom', 'published', 'Wales', 'Cardiff', 'Cardiff', 'CF10 3DX', 51.4870, -3.1780, 'An elegant tearoom in Bute Park with outdoor seating and a warm dog welcome.', 'Set in the Gatekeeper''s cottage at the entrance to Bute Park. Dogs welcome at all outdoor tables.', 'A beautiful park tearoom where dogs are welcome outdoors. Perfect after Bute Park.', 'no', 'yes', 'no', 'yes', 'yes', 'yes', 'no', 'yes', 'yes', 'yes', 'low', 'relaxed', 'yes', 'no', 'no', 'yes', 'yes', 'Weekend mornings', 'Afternoon tea, cakes, sandwiches, loose-leaf tea', '££', 'warm_little_welcome', 72, ARRAY['Warm Little Welcome', 'Perfect after walkies', 'Rainy day rescue'], ARRAY['bute-park-cardiff'], 'personal_visit', '2026-06-25');

-- NOTTINGHAM: The Canal House
INSERT INTO venues (slug, name, venue_type, status, region, county, town, postcode, latitude, longitude, summary, editorial_review, tiny_dog_verdict, dogs_indoors, dogs_outdoors, dogs_throughout, covered_outdoor_seating, quiet_seating, spacious_tables, enclosed_garden, puppy_suitable, nervous_dog_suitable, multiple_dogs_welcome, escape_risk, noise_level, water_bowls, free_dog_treats, parking_available, accessible_entrance, nearby_green_space, best_visit_times, food_and_drink_summary, price_band, welcome_label, welcome_score, feature_labels, nearby_walk_slugs, verification_method, last_verified_date)
VALUES ('the-canal-house-nottingham', 'The Canal House', 'pub', 'published', 'East Midlands', 'Nottinghamshire', 'Nottingham', 'NG1 7EH', 52.9535, -1.1510, 'A stunning canal-side pub built over a canal basin with glass floor panels.', 'A unique pub — canal runs underneath through glass floor panels. Dogs welcome in main bar areas.', 'A fascinating setting with a relaxed dog-friendly atmosphere.', 'yes', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'yes', 'yes', 'yes', 'low', 'moderate', 'yes', 'no', 'yes', 'yes', 'yes', 'Weekday afternoons', 'Gastro pub food, real ales, weekend brunch', '££', 'warm_little_welcome', 74, ARRAY['Warm Little Welcome', 'Little paws welcome inside'], ARRAY['wollaton-park-nottingham'], 'venue_confirmation', '2026-06-12');

-- NEWCASTLE: The Broad Chare
INSERT INTO venues (slug, name, venue_type, status, region, county, town, postcode, latitude, longitude, summary, editorial_review, tiny_dog_verdict, dogs_indoors, dogs_outdoors, dogs_throughout, covered_outdoor_seating, quiet_seating, spacious_tables, enclosed_garden, puppy_suitable, nervous_dog_suitable, multiple_dogs_welcome, escape_risk, noise_level, water_bowls, free_dog_treats, parking_available, accessible_entrance, nearby_green_space, best_visit_times, food_and_drink_summary, price_band, welcome_label, welcome_score, feature_labels, nearby_walk_slugs, verification_method, last_verified_date)
VALUES ('the-broad-chare-newcastle', 'The Broad Chare', 'pub', 'published', 'North East', 'Tyne and Wear', 'Newcastle', 'NE1 3DQ', 54.9690, -1.5990, 'A proper quayside pub near the Tyne Bridge with dogs welcome in the ground floor bar.', 'Chef Terry Laybourne''s quayside pub. Dogs welcome in the characterful ground floor bar.', 'A quality quayside pub where tiny dogs are welcome in the downstairs bar.', 'yes', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'yes', 'yes', 'yes', 'low', 'moderate', 'yes', 'no', 'no', 'yes', 'yes', 'Weekday lunchtimes', 'Gastropub classics, local ales, wines', '££', 'warm_little_welcome', 72, ARRAY['Warm Little Welcome', 'Little paws welcome inside', 'Best for a calm lunch'], ARRAY['jesmond-dene-newcastle'], 'personal_visit', '2026-06-30');

-- BATH: The Green Bird Café
INSERT INTO venues (slug, name, venue_type, status, region, county, town, postcode, latitude, longitude, summary, editorial_review, tiny_dog_verdict, dogs_indoors, dogs_outdoors, dogs_throughout, covered_outdoor_seating, quiet_seating, spacious_tables, enclosed_garden, puppy_suitable, nervous_dog_suitable, multiple_dogs_welcome, escape_risk, noise_level, water_bowls, free_dog_treats, parking_available, accessible_entrance, nearby_green_space, best_visit_times, food_and_drink_summary, price_band, welcome_label, welcome_score, feature_labels, nearby_walk_slugs, verification_method, last_verified_date)
VALUES ('the-green-bird-cafe-bath', 'The Green Bird Café', 'cafe', 'published', 'South West', 'Somerset', 'Bath', 'BA1 2QZ', 51.3820, -2.3590, 'An independent café near the Royal Crescent with dogs welcome inside.', 'Lovely independent café near one of Bath''s best walking spots. Dogs welcome inside.', 'A homely café where tiny dogs are genuinely welcomed.', 'yes', 'yes', 'yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'yes', 'low', 'relaxed', 'yes', 'yes', 'no', 'yes', 'yes', 'Mid-morning weekdays', 'Homemade cakes, brunch, lunch, specialty coffee', '£', 'tiny_dog_favourite', 86, ARRAY['Tiny Dog Favourite', 'Little paws welcome inside', 'Treats behind the bar'], ARRAY['bath-skyline-walk-short'], 'personal_visit', '2026-07-01');

-- YORK: House of Trembling Madness
INSERT INTO venues (slug, name, venue_type, status, region, county, town, postcode, latitude, longitude, summary, editorial_review, tiny_dog_verdict, dogs_indoors, dogs_outdoors, dogs_throughout, covered_outdoor_seating, quiet_seating, spacious_tables, enclosed_garden, puppy_suitable, nervous_dog_suitable, multiple_dogs_welcome, escape_risk, noise_level, water_bowls, free_dog_treats, parking_available, accessible_entrance, nearby_green_space, best_visit_times, food_and_drink_summary, price_band, welcome_label, welcome_score, feature_labels, nearby_walk_slugs, verification_method, last_verified_date)
VALUES ('the-house-of-trembling-madness-york', 'House of Trembling Madness', 'pub', 'published', 'Yorkshire', 'North Yorkshire', 'York', 'YO1 8BJ', 53.9610, -1.0810, 'A medieval drinking hall above a bottle shop on Stonegate with dogs welcome.', 'A genuinely unique York experience — medieval hall with antlers, taxidermy and enormous beer list. Dogs welcome.', 'An eccentric medieval pub where dogs are part of the charm.', 'yes', 'no', 'yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'yes', 'low', 'moderate', 'yes', 'yes', 'no', 'yes', 'yes', 'Early evening', 'Craft beers, real ales, cheese boards', '££', 'tiny_dog_favourite', 84, ARRAY['Tiny Dog Favourite', 'Little paws welcome inside', 'Treats behind the bar'], ARRAY['york-city-walls-loop'], 'personal_visit', '2026-06-14');

-- SHEFFIELD: Tamper Coffee
INSERT INTO venues (slug, name, venue_type, status, region, county, town, postcode, latitude, longitude, summary, editorial_review, tiny_dog_verdict, dogs_indoors, dogs_outdoors, dogs_throughout, covered_outdoor_seating, quiet_seating, spacious_tables, enclosed_garden, puppy_suitable, nervous_dog_suitable, multiple_dogs_welcome, escape_risk, noise_level, water_bowls, free_dog_treats, parking_available, accessible_entrance, nearby_green_space, best_visit_times, food_and_drink_summary, price_band, welcome_label, welcome_score, feature_labels, nearby_walk_slugs, verification_method, last_verified_date)
VALUES ('tamper-coffee-sellers-wheel-sheffield', 'Tamper Coffee — Sellers Wheel', 'cafe', 'published', 'Yorkshire', 'South Yorkshire', 'Sheffield', 'S1 4PF', 53.3810, -1.4690, 'A New Zealand-inspired brunch café in a converted silversmith workshop.', 'Sheffield''s go-to for brunch and specialty coffee. Dogs welcome inside the industrial space.', 'A stylish brunch spot with a genuine dog-friendly policy.', 'yes', 'no', 'yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'low', 'moderate', 'yes', 'no', 'no', 'yes', 'yes', 'Early weekday morning', 'NZ-inspired brunch, specialty coffee, cakes', '££', 'warm_little_welcome', 74, ARRAY['Warm Little Welcome', 'Little paws welcome inside'], ARRAY['endcliffe-park-sheffield'], 'personal_visit', '2026-06-08');

-- =============================================
-- WALKS
-- =============================================

-- LONDON: Hyde Park
INSERT INTO walks (slug, status, title, strapline, summary, region, county, nearest_town, latitude, longitude, distance_miles, duration_minutes, difficulty, route_type, environments, surfaces, gradient, stile_count, livestock, road_exposure, escape_risk, off_lead, puppy_friendly, buggy_friendly, quietness, weather_exposure, winter_suitable, parking_available, parking_notes, toilets_available, toilets_notes, cafe_name, cafe_dog_friendly, why_tiny_dogs_love_it, rating_total, rating_band, rating_positives, rating_caution, last_verified, featured)
VALUES ('hyde-park-serpentine-loop', 'published', 'Hyde Park — Serpentine Loop', 'A flat lakeside stroll through London''s most famous park', 'A gentle circuit around the Serpentine lake. Flat, paved paths, benches and a café.', 'London', 'Greater London', 'London', 51.5065, -0.1680, 1.8, 40, 'easy', 'circular', ARRAY['park','lakeside','urban'], ARRAY['paved','gravel'], 'mostly-flat', 0, 'none-known', 'none', 'low', 'limited', true, 'yes', 'variable', 'mixed', true, true, 'Underground parking or street parking', true, 'Multiple locations', 'The Magazine Serpentine', true, ARRAY['Completely flat paths','Plenty of rest benches','Central London convenience'], 86, 'Perfect for tiny paws', ARRAY['Flat and accessible','Excellent café stop'], 'Busy at weekends — keep on lead', '2026-07-01', true);

-- LONDON: Hampstead Heath
INSERT INTO walks (slug, status, title, strapline, summary, region, county, nearest_town, latitude, longitude, distance_miles, duration_minutes, difficulty, route_type, environments, surfaces, gradient, stile_count, livestock, road_exposure, escape_risk, off_lead, puppy_friendly, buggy_friendly, quietness, weather_exposure, winter_suitable, parking_available, parking_notes, toilets_available, toilets_notes, cafe_name, cafe_dog_friendly, why_tiny_dogs_love_it, rating_total, rating_band, rating_positives, rating_caution, last_verified, featured)
VALUES ('hampstead-heath-parliament-hill', 'published', 'Hampstead Heath — Parliament Hill', 'London skyline views from a gentle hilltop walk', 'A short circuit through southern Hampstead Heath with panoramic London views.', 'London', 'Greater London', 'London', 51.5560, -0.1500, 1.5, 35, 'easy', 'circular', ARRAY['park','countryside'], ARRAY['grass','gravel','mud'], 'gentle', 0, 'none-known', 'none', 'low', 'some-sections', true, 'dry-weather-only', 'variable', 'mixed', true, true, 'Street parking on surrounding roads', true, 'At the Lido', 'The Spaniards Inn', true, ARRAY['Off-lead sections for confident dogs','Stunning skyline views','Direct pub access afterwards'], 82, 'Easy little adventure', ARRAY['Great off-lead areas','Iconic views'], 'Muddy in winter', '2026-06-28', true);

-- BIRMINGHAM: Cannon Hill Park
INSERT INTO walks (slug, status, title, strapline, summary, region, county, nearest_town, latitude, longitude, distance_miles, duration_minutes, difficulty, route_type, environments, surfaces, gradient, stile_count, livestock, road_exposure, escape_risk, off_lead, puppy_friendly, buggy_friendly, quietness, weather_exposure, winter_suitable, parking_available, parking_notes, toilets_available, toilets_notes, cafe_name, cafe_dog_friendly, why_tiny_dogs_love_it, rating_total, rating_band, rating_positives, rating_caution, last_verified, featured)
VALUES ('cannon-hill-park-birmingham', 'published', 'Cannon Hill Park', 'A peaceful city park with lakes and flat paths', 'A flat walk through Birmingham''s best city park with ornamental gardens and lakes.', 'West Midlands', 'West Midlands', 'Birmingham', 52.4550, -1.9060, 1.4, 30, 'easy', 'circular', ARRAY['park','lakeside','urban'], ARRAY['paved','gravel'], 'mostly-flat', 0, 'none-known', 'none', 'low', 'limited', true, 'yes', 'variable', 'mixed', true, true, 'Free car park at Russell Road', true, 'Near the mac arts centre', 'MAC Café', true, ARRAY['Completely flat lakeside paths','Well-maintained and clean','Arts centre café nearby'], 88, 'Perfect for tiny paws', ARRAY['Flat and traffic-free','Good facilities'], 'Busy with families at weekends', '2026-06-15', true);

-- EDINBURGH: Inverleith Park
INSERT INTO walks (slug, status, title, strapline, summary, region, county, nearest_town, latitude, longitude, distance_miles, duration_minutes, difficulty, route_type, environments, surfaces, gradient, stile_count, livestock, road_exposure, escape_risk, off_lead, puppy_friendly, buggy_friendly, quietness, weather_exposure, winter_suitable, parking_available, parking_notes, toilets_available, toilets_notes, cafe_name, cafe_dog_friendly, why_tiny_dogs_love_it, rating_total, rating_band, rating_positives, rating_caution, last_verified, featured)
VALUES ('inverleith-park-edinburgh', 'published', 'Inverleith Park — Botanics Loop', 'Castle views and botanical gardens in north Edinburgh', 'A flat loop through Inverleith Park with views of Edinburgh Castle.', 'Scotland', 'City of Edinburgh', 'Edinburgh', 55.9650, -3.2100, 1.3, 30, 'easy', 'circular', ARRAY['park','urban'], ARRAY['paved','grass'], 'mostly-flat', 0, 'none-known', 'none', 'low', 'some-sections', true, 'yes', 'usually-quiet', 'mixed', true, true, 'Street parking on Inverleith Row', true, 'At the Botanics', 'The Terrace Café Botanics', true, ARRAY['Flat paths with castle views','Quiet compared to Princes Street','Dog-friendly café outdoors'], 90, 'Perfect for tiny paws', ARRAY['Quiet and scenic','Flat throughout'], 'Dogs not allowed inside the Botanics', '2026-06-20', true);

-- BRISTOL: Harbourside Loop
INSERT INTO walks (slug, status, title, strapline, summary, region, county, nearest_town, latitude, longitude, distance_miles, duration_minutes, difficulty, route_type, environments, surfaces, gradient, stile_count, livestock, road_exposure, escape_risk, off_lead, puppy_friendly, buggy_friendly, quietness, weather_exposure, winter_suitable, parking_available, parking_notes, toilets_available, toilets_notes, cafe_name, cafe_dog_friendly, why_tiny_dogs_love_it, rating_total, rating_band, rating_positives, rating_caution, last_verified, featured)
VALUES ('bristol-harbourside-loop', 'published', 'Bristol Harbourside Loop', 'A flat waterfront stroll through the Floating Harbour', 'A paved loop along Bristol''s Floating Harbour past boats, cafés and SS Great Britain.', 'South West', 'Bristol', 'Bristol', 51.4490, -2.6000, 1.6, 35, 'easy', 'circular', ARRAY['urban','lakeside'], ARRAY['paved'], 'mostly-flat', 0, 'none-known', 'low', 'low', 'limited', true, 'yes', 'variable', 'mixed', true, true, 'Pay and display at Millennium Square', true, 'Multiple locations', 'The Grain Barge', true, ARRAY['Flat paved paths throughout','Multiple café stops','Interesting boats and activity'], 84, 'Easy little adventure', ARRAY['Flat and paved','Great café options'], 'Keep on lead near unfenced harbour edge', '2026-06-22', true);

-- GLASGOW: Kelvingrove Park
INSERT INTO walks (slug, status, title, strapline, summary, region, county, nearest_town, latitude, longitude, distance_miles, duration_minutes, difficulty, route_type, environments, surfaces, gradient, stile_count, livestock, road_exposure, escape_risk, off_lead, puppy_friendly, buggy_friendly, quietness, weather_exposure, winter_suitable, parking_available, parking_notes, toilets_available, toilets_notes, cafe_name, cafe_dog_friendly, why_tiny_dogs_love_it, rating_total, rating_band, rating_positives, rating_caution, last_verified, featured)
VALUES ('kelvingrove-park-glasgow', 'published', 'Kelvingrove Park', 'A riverside walk through Glasgow''s finest Victorian park', 'A gentle circuit through Kelvingrove Park along the River Kelvin.', 'Scotland', 'Glasgow', 'Glasgow', 55.8680, -4.2830, 1.2, 25, 'easy', 'circular', ARRAY['park','urban'], ARRAY['paved','gravel'], 'gentle', 0, 'none-known', 'none', 'low', 'limited', true, 'yes', 'variable', 'mixed', true, true, 'Street parking or university car parks', true, 'At Kelvingrove Museum', 'Kelvingrove Café', true, ARRAY['Beautiful riverside paths','Short and sheltered','Museum café welcomes dogs outdoors'], 86, 'Perfect for tiny paws', ARRAY['Short and sheltered','Scenic setting'], 'Some slopes near the river', '2026-06-18', false);

-- CARDIFF: Bute Park
INSERT INTO walks (slug, status, title, strapline, summary, region, county, nearest_town, latitude, longitude, distance_miles, duration_minutes, difficulty, route_type, environments, surfaces, gradient, stile_count, livestock, road_exposure, escape_risk, off_lead, puppy_friendly, buggy_friendly, quietness, weather_exposure, winter_suitable, parking_available, parking_notes, toilets_available, toilets_notes, cafe_name, cafe_dog_friendly, why_tiny_dogs_love_it, rating_total, rating_band, rating_positives, rating_caution, last_verified, featured)
VALUES ('bute-park-cardiff', 'published', 'Bute Park — River Taff Trail', 'A flat riverside walk through Cardiff''s green heart', 'An easy riverside stroll through Bute Park from Cardiff Castle to Blackweir.', 'Wales', 'Cardiff', 'Cardiff', 51.4880, -3.1850, 1.4, 30, 'easy', 'out-and-back', ARRAY['park','urban'], ARRAY['paved','gravel'], 'mostly-flat', 0, 'none-known', 'none', 'low', 'limited', true, 'yes', 'usually-quiet', 'sheltered', true, true, 'City centre car parks nearby', true, 'In the park', 'Pettigrew Tea Rooms', true, ARRAY['Flat riverside paths','Sheltered by mature trees','Pettigrew tearoom at the entrance'], 88, 'Perfect for tiny paws', ARRAY['Flat and sheltered','Lovely café stop'], 'Keep on lead near the river', '2026-06-25', true);

-- NOTTINGHAM: Wollaton Park
INSERT INTO walks (slug, status, title, strapline, summary, region, county, nearest_town, latitude, longitude, distance_miles, duration_minutes, difficulty, route_type, environments, surfaces, gradient, stile_count, livestock, road_exposure, escape_risk, off_lead, puppy_friendly, buggy_friendly, quietness, weather_exposure, winter_suitable, parking_available, parking_notes, toilets_available, toilets_notes, cafe_name, cafe_dog_friendly, why_tiny_dogs_love_it, rating_total, rating_band, rating_positives, rating_caution, last_verified, featured)
VALUES ('wollaton-park-nottingham', 'published', 'Wollaton Park — Deer Park Circuit', 'A gentle parkland walk around a stately home', 'A flat circuit around Wollaton Hall and its deer park with wide paths.', 'East Midlands', 'Nottinghamshire', 'Nottingham', 52.9470, -1.2080, 1.8, 40, 'easy', 'circular', ARRAY['park','countryside'], ARRAY['gravel','grass'], 'mostly-flat', 0, 'none-known', 'none', 'low', 'limited', true, 'yes', 'variable', 'mixed', true, true, 'Free parking at Wollaton Park', true, 'At the courtyard', 'Wollaton Hall Café', true, ARRAY['Flat paths through parkland','Free entry and parking','Interesting deer to watch'], 84, 'Easy little adventure', ARRAY['Free entry','Flat and spacious'], 'Dogs on lead due to deer', '2026-06-12', false);

-- NEWCASTLE: Jesmond Dene
INSERT INTO walks (slug, status, title, strapline, summary, region, county, nearest_town, latitude, longitude, distance_miles, duration_minutes, difficulty, route_type, environments, surfaces, gradient, stile_count, livestock, road_exposure, escape_risk, off_lead, puppy_friendly, buggy_friendly, quietness, weather_exposure, winter_suitable, parking_available, parking_notes, toilets_available, toilets_notes, cafe_name, cafe_dog_friendly, why_tiny_dogs_love_it, rating_total, rating_band, rating_positives, rating_caution, last_verified, featured)
VALUES ('jesmond-dene-newcastle', 'published', 'Jesmond Dene', 'A hidden wooded valley in the heart of Newcastle', 'A sheltered walk along the Ouseburn through the wooded gorge of Jesmond Dene.', 'North East', 'Tyne and Wear', 'Newcastle', 54.9830, -1.5880, 1.5, 35, 'easy', 'out-and-back', ARRAY['woodland','urban'], ARRAY['paved','gravel'], 'gentle', 0, 'none-known', 'none', 'low', 'limited', true, 'dry-weather-only', 'usually-quiet', 'sheltered', true, true, 'Small car park at entrance', true, 'At Millfield House', 'Jesmond Dene Café', true, ARRAY['Sheltered woodland in the city','Quiet and peaceful','Beautiful in autumn'], 86, 'Perfect for tiny paws', ARRAY['Sheltered and quiet','Beautiful scenery'], 'Steps at some sections', '2026-06-30', true);

-- BATH: Skyline Walk
INSERT INTO walks (slug, status, title, strapline, summary, region, county, nearest_town, latitude, longitude, distance_miles, duration_minutes, difficulty, route_type, environments, surfaces, gradient, stile_count, livestock, road_exposure, escape_risk, off_lead, puppy_friendly, buggy_friendly, quietness, weather_exposure, winter_suitable, parking_available, parking_notes, toilets_available, toilets_notes, cafe_name, cafe_dog_friendly, why_tiny_dogs_love_it, rating_total, rating_band, rating_positives, rating_caution, last_verified, featured)
VALUES ('bath-skyline-walk-short', 'published', 'Bath Skyline — Bathwick Fields', 'Rolling meadows with panoramic views over Bath', 'A short section of the Bath Skyline Walk across Bathwick Fields.', 'South West', 'Somerset', 'Bath', 51.3780, -2.3420, 1.3, 30, 'easy', 'circular', ARRAY['countryside','park'], ARRAY['grass','gravel'], 'gentle', 0, 'possible', 'none', 'low', 'some-sections', true, 'dry-weather-only', 'usually-quiet', 'exposed', true, true, 'National Trust car park', false, NULL, NULL, false, ARRAY['Gentle meadow paths','Panoramic city views','Quiet and uncrowded'], 78, 'Easy little adventure', ARRAY['Quiet meadows','Beautiful views'], 'Exposed to wind on hilltop', '2026-07-01', false);

-- YORK: City Walls
INSERT INTO walks (slug, status, title, strapline, summary, region, county, nearest_town, latitude, longitude, distance_miles, duration_minutes, difficulty, route_type, environments, surfaces, gradient, stile_count, livestock, road_exposure, escape_risk, off_lead, puppy_friendly, buggy_friendly, quietness, weather_exposure, winter_suitable, parking_available, parking_notes, toilets_available, toilets_notes, cafe_name, cafe_dog_friendly, why_tiny_dogs_love_it, rating_total, rating_band, rating_positives, rating_caution, last_verified, featured)
VALUES ('york-city-walls-loop', 'published', 'York City Walls', 'Walk the medieval walls circling the historic city', 'A paved walk along sections of York''s ancient city walls with Minster views.', 'Yorkshire', 'North Yorkshire', 'York', 53.9590, -1.0820, 1.2, 30, 'easy', 'linear', ARRAY['urban'], ARRAY['paved'], 'mostly-flat', 0, 'none-known', 'low', 'low', 'limited', true, 'yes', 'often-busy', 'exposed', true, false, NULL, true, 'Multiple access points', NULL, false, ARRAY['Flat paved surface','Historic views','Multiple exit points if tiny legs tire'], 80, 'Easy little adventure', ARRAY['Flat and paved','Fascinating history'], 'Narrow in places — pick up tiny dogs when busy', '2026-06-14', false);

-- SHEFFIELD: Endcliffe Park
INSERT INTO walks (slug, status, title, strapline, summary, region, county, nearest_town, latitude, longitude, distance_miles, duration_minutes, difficulty, route_type, environments, surfaces, gradient, stile_count, livestock, road_exposure, escape_risk, off_lead, puppy_friendly, buggy_friendly, quietness, weather_exposure, winter_suitable, parking_available, parking_notes, toilets_available, toilets_notes, cafe_name, cafe_dog_friendly, why_tiny_dogs_love_it, rating_total, rating_band, rating_positives, rating_caution, last_verified, featured)
VALUES ('endcliffe-park-sheffield', 'published', 'Endcliffe Park — Porter Brook Trail', 'A woodland stream walk from city edge into the Peak District', 'Follow Porter Brook upstream through a chain of parks towards the moors.', 'Yorkshire', 'South Yorkshire', 'Sheffield', 53.3680, -1.5100, 1.4, 30, 'easy', 'out-and-back', ARRAY['park','woodland','urban'], ARRAY['paved','gravel'], 'gentle', 0, 'none-known', 'none', 'low', 'some-sections', true, 'yes', 'variable', 'sheltered', true, true, 'Free car park at Endcliffe Park', true, 'At the café', 'Endcliffe Park Café', true, ARRAY['Sheltered stream-side paths','Off-lead areas available','Multiple parks linked together'], 86, 'Perfect for tiny paws', ARRAY['Sheltered and scenic','Good off-lead sections'], 'Can be muddy after rain', '2026-06-08', true);
